### ISSUE TITLE
Start the move from typescript to web assembly

### ISSUE THREAD

**Issue by oplik0** [denorg/scrypt#2]
While no good wasm scrypt implementation exists (the only one I found didn't work for me, which is probably caused by it using an older version of rust and wasm-pack. It's also just possible that the fork didn't actually fix the problem that made original incompatible with web assembly), there might be web assembly versions of some of the functions used by scrypt like pbkdf2 or perhaps salsa20 that might be modified to only use core with 8 rounds. So at least partial transition might be possible now, even if full one will have to wait until I or someone else makes something that works.

**Comment by oplik0** [comment]
Thanks to the work of [skdltmxn](https://github.com/skdltmxn) there is now a nice build script for wasm-pack that works with deno that was used for [std/hash](https://deno.land/std/hash/) [wasm implementation](https://github.com/denoland/deno/pull/6292).

The performance was improved by A LOT. A quick benchmark with standard parameters changed from ~650ms to ~180ms. I'll try to run some more benchmarks later, but the performance gains are really big.
And it still doesn't need any privileges to run!

**Comment by AnandChowdhary** [comment]
Also, this works! https://twitter.com/_denorg/status/1274720537038766084
