### ISSUE TITLE
Broken std dependency

### ISSUE THREAD

**Issue by fer22f** [denorg/scrypt#4]
```
error: TS2305 [ERROR]: Module '"https://deno.land/std@0.103.0/encoding/hex.ts"' has no exported member 'encodeToString'.
import { encodeToString as hexencode } from "https://deno.land/std/encoding/hex.ts";
         ~~~~~~~~~~~~~~
    at https://deno.land/x/scrypt@v2.0.0/lib/scrypt.ts:3:10
```

**Comment by oplik0** [comment]
Fixed by #5

**Comment by elisee** [comment]
Will this be released to deno.land/x/scrypt soon? it's still @2.0.0

**Comment by oplik0** [comment]
Sorry for not responding @elisee, I was a bit busy - you guessed correctly with the update webhook. I don't have the permissions to fix it though, so I'm waiting on the owners of the org.

When they fix it or I have the privileges to do it myself I'll update the `deno.land` version. In the meantime I published the current version on nest.land: https://nest.land/package/scrypt
